### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by maelle** [ropensci/hathi#3]
Suggestions:

* Add a link to HathiTrust in the README/vignette

* Write in the package DESCRIPTION and the repo description (and the README+Vignette) what it is. 

* Add a few repo topics.

Thanks 😸

**Comment by sckott** [comment]
thanks!  will do. 

we do have some topics already, are you suggesting different topics?

**Comment by maelle** [comment]
I know see the repo topics added programmatically by me 😉 anything related to what hathi is would be nice 😀

**Comment by sckott** [comment]
okay, will do

**Comment by sckott** [comment]
done, i think
